apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server-plan
  namespace: cattle-system
spec:
  concurrency: 2
  coordinate: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  prepare:
    planName: k3s-server-plan # <-- Blocks workers until the master plan hits 100% success
  serviceAccountName: system-upgrade
  version: v1.34.8+k3s1 # <-- Must match the target version above
  upgrade:
    image: rancher/k3s-upgrade