---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: system
spec:
  releaseName: node-feature-discovery
  chart:
    spec:
      chart: node-feature-discovery
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 15m
  timeout: 5m

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace