---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: '1.*'
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: longhorn-system
      interval: 24h

  values:
    crds:
      enabled: true
      keep: true