apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-ssd
  namespace: downloads
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 800Gi
