apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads-ssd
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-ssd
  resources:
    requests:
      storage: 800Gi
