---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: system
spec:
  version: 0.17.1
  valuesFrom:
    - kind: ConfigMap
      name: system-node-feature-discovery-config-map-helm-values
      valuesKey: values.yaml