---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mylar
  namespace: system
spec:
  releaseName: mylar
  chart:
    spec:
      chart: mylar
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 15m
  timeout: 5m