apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  ENCRYPTION_KEY: "5bf6828d73cdc78ced8c20bb04328796"
  AUTH_SECRET: "yMVrwYIoP+ADcMJEv2ZzHFvJrPRfA0+COqgX9/cmfO0="
  DB_CONNECTION_URI: "postgresql://infisical:Q0mk7BphGrKmKO51RG9BNpilkPb73sDMwSfFU1VqdTU6TejrZpuhOfkjIHqM4Fog@postgres-rw.database:5432/infisicalDB"
  REDIS_URL: "redis://valkey.database.svc.cluster.local:6379"