apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  ENCRYPTION_KEY: "2fd85ca9a76638f2d204a21ab2383342d457648c7a46811303feef8db3369ddf"
  ROOT_ENCRYPTION_KEY: "a3a525780af40391fcbb5707335835ceca0620e6b4b57f10733660713814ffdc"
  AUTH_SECRET: "87a59345206d454abc73e6fa26321f3aa93fcc6a5b29cc53c26f59be4facf2f0"
  DB_CONNECTION_URL: "postgresql://postgres:postgres-password@postgresql.infisical.svc.cluster.local:5432/infisical"
  REDIS_URL: "redis://redis-master.infisical.svc.cluster.local:6379"