apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: infisical
type: Opaque
stringData:
  ENCRYPTION_KEY: "ldH8pX5wNf3YvK6q9XzBCd+mN72K3P9v8xYnZaeR4uQ="
  AUTH_SECRET: "87a59345206d454abc73e6fa26321f3aa93fcc6a5b29cc53c26f59be4facf2f0"
  DB_CONNECTION_URL: "postgresql://postgres:postgres-password@postgresql.infisical.svc.cluster.local:5432/infisical"
  REDIS_URL: "redis://redis-master.infisical.svc.cluster.local:6379"