apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: emqx-mqtt-tls
  namespace: messaging
spec:
  secretName: emqx-mqtt-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - mqtt.peterduckett.me
