---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: system
spec:
  releaseName: nzbget
  chart:
    spec:
      chart: nzbget
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 15m
  timeout: 5m