apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cilium
  namespace: flux-system
spec:
  interval: 15m
  prune: true
  wait: true # Flux waits for the core Cilium pods to be 100% healthy
  timeout: 5m
  path: ./infrastructure/cilium/overlays/prod
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-cilium-config
  namespace: flux-system
spec:
  interval: 15m
  prune: true
  wait: true
  timeout: 2m
  # Points to the new subfolder containing your BGP pools
  path: ./infrastructure/cilium/overlays/prod/bgp-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  # THE FIX: Do not apply this until the main Cilium installation succeeds!
  dependsOn:
    - name: infrastructure-cilium
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-traefik
  namespace: flux-system
spec:
  interval: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/traefik/overlays/prod # Must match your Git path exactly!
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  path: ./infrastructure/cert-manager/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system


    