apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-helm-repositories
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  path: ./infrastructure/helm-repositories
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
