apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/flight-tracking-storage
  - ultrafeeder
  - flightradar24
  - piaware
  - planefinder
  - adsbhub
  - opensky-network
  - airnavradar
