---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart:
    spec:
      chart: traefik
      version: '34.x'
      sourceRef:
        kind: HelmRepository
        name: traefik-repository
        namespace: kube-system
      interval: 24h
  interval: 1h
  timeout: 5m

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  experimental:
    http3: true