apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  values:
    # Enable the dashboard
    ingressRoute:
      dashboard:
        enabled: true

    # SSL Enforcement
    ports:
      web:
        redirectTo:
          port: websecure
      websecure:
        tls:
          enabled: true

    # Layout rules for your RK1 and RPi mixed cluster
    deployment:
      replicas: 3
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - traefik
              topologyKey: kubernetes.io/hostname