---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: downloads
spec:
  releaseName: overseerr
  chart:
    spec:
      chart: app-template
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  timeout: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/overseerr
              tag: latest
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: "Etc/UTC"
    service:
      main:
        controller: main
        ports:
          http:
            port: 5055
    persistence:
      config:
        existingClaim: overseerr-config
        globalMounts:
          - path: /config
