---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: overseerr
  namespace: downloads
spec:
  releaseName: overseerr
  chart:
    spec:
      chart: app-template
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  timeout: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/overseerr
              tag: latest
            env:
              PUID: "1000"
              PGID: "1000"
              TZ: "Etc/UTC"
            resources:
              requests:
                cpu: 15m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 5055
    ingress:
      main:
        className: traefik
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: &host overseerr.peterduckett.me
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - secretName: overseerr-tls
            hosts:
              - *host
    persistence:
      config:
        existingClaim: overseerr-config
        globalMounts:
          - path: /config
