apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nzbget
  namespace: downloads
spec:
  values:
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: node-2-3
    persistence:
      downloads:
        existingClaim: downloads-ssd
        globalMounts:
          - path: /downloads
