---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: cilium
    namespace: flux-system
  interval: 5m50s
  releaseName: cilium
  targetNamespace: kube-system
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
