apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  values:
  # Increase timeouts for BPF compilation and proxy interactions
    bpf:
      compileTimeout: "15m"
    ipv4:
      enabled: true
    ipv6:
      enabled: true
    ipam:
      operator:
        clusterPoolIPv6PodCIDRList: ["2001:db8:42::/56"]
