---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 30m
  chart:
    spec:
      chart: rancher
      version: '2.*'
      sourceRef:
        kind: HelmRepository
        name: rancher-repository
        namespace: cattle-system
      interval: 24h