---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bazarr
  namespace: downloads
spec:
  chart:
    spec:
      version: ">=21.6.0"
  valuesFrom:
    - kind: ConfigMap
      name: downloads-bazarr-config-map-helm-values
      valuesKey: values.yaml