---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: autobrr
  namespace: downloads
spec:
  chart:
    spec:
      version: ">=10.0.0"
  valuesFrom:
    - kind: ConfigMap
      name: downloads-autobrr-config-map-helm-values
      valuesKey: values.yaml