---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wizarr
  namespace: system
spec:
  releaseName: wizarr
  chart:
    spec:
      chart: wizarr
      version: '10.1.*'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  interval: 15m
  timeout: 5m